services:
  server:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src/var/www/html:delegated # optimization
    ports:
      - '3000:9000'
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  # Utilities
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      # Utility Container: Makes it so files being created by composer, inside the container, will be mirrored back on the src folder in the host machine
      - ./src:/var/www/html
  artisan:
  npm: